### ISSUE TITLE
Install difficulties

### ISSUE THREAD

**Issue by heartlocket** [maua-maua-maua/maua#5] opened 2022-09-04 19:19 UTC
Keep seeing this repeated error on install

Running command git submodule update --init --recursive -q
  error: unable to create file docs/d0/d14/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compatie5920c849e839ebb9f8c57349c900796.html: Filename too long
_attn/cutlass'
  error: subprocess-exited-with-error

  × git submodule update --init --recursive -q did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by JCBrouwer** [comment] 2022-09-05 15:35
duplicate of #4

**Closed as completed by JCBrouwer** 2022-09-05 15:35 UTC
